### ISSUE TITLE
 proto missing fields 9 and 10 

### ISSUE THREAD

**Issue by 3052** [larsenv/Kanopy-Downloader#3]
https://github.com/larsenv/Kanopy-Downloader/blob/68137880baf106404ab590b555d56c3172d1f466/pywidevine/cdm/formats/wv_proto3.proto#L38-L53

**Comment by larsenv** [comment]
Sorry for the delay, what is supposed to go there?

**Comment by 3052** [comment]
https://github.com/devine-dl/pywidevine/blob/7ea2a72a8c12a607f0b67fd7e53f669a41d7721e/pywidevine/license_protocol.proto#L611-L621

**Comment by larsenv** [comment]
Could you please explain why this is needed and I'll add it?

**Comment by 3052** [comment]
if someone wanted to manually implement their own software CDM, they would want these field documented because they are required by the server
